try {
o0('Test #' + index + ' - Error handler #2 called with err = ' + o11)({}, this);
}catch(e)try { {} } catch(e) {}try { {} } catch(e) {}
try {
o935 = o3.propertyIsEnumerable('caller');
}catch(e){}